services:
  api: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 9000:9000
    volumes:
      - ./server/src/:/opt/app
  pg:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: pg
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - ./database/src/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    